name: Deploy
on:
  release:
    types: [published]
jobs:
  deploy_source:
    name: Build and deploy Lambda
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy Ghost theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}